language: go

go:
  - 1.12.x

# before we deploy, we go build for all operating systems we would like to support
before_deploy:
  - mkdir -p release
  - "GOOS=linux GOARCH=amd64 go build -o release/gitblame"
  - "GOOS=windows GOARCH=amd64 go build -o release/gitblame.exe"

deploy:
  provider: releases
  api_key: ${GITHUB_API_KEY}
  file:
    - "release/gitblame"
    - "release/gitblame.exe"
  skip_cleanup: true

